const data = {
    products:[
        {
            _id:'1', 
            name:'Nike Slim Shirt',
            category: 'Shirts',
            image:'./images/p1.jpg', 
            price:120,
            brand:'Nike', 
            rating:2.5, 
            numReviews:5,
            description:'hight quality product',
        },
        {
            _id:'2', 
            name:'Nike Shirt',
            category: 'Shirts',
            image:'./images/p2.jpg', 
            price:100,
            brand:'Nike', 
            rating:4, 
            numReviews:10,
            description:'hight quality product',
        },
        {
            _id:'3', 
            name:'Adidas Slim Shirt',
            category: 'Shirts',
            image:'./images/p3.jpg', 
            price:120,
            brand:'Adidas', 
            rating:4.5, 
            numReviews:10,
            description:'hight quality product',
        },
        {
            _id:'4', 
            name:'Nike Slim pant',
            category: 'Shirts',
            image:'./images/p4.jpg', 
            price:110,
            brand:'Nike', 
            rating:3, 
            numReviews:2,
            description:'hight quality product',
        },
        {
            _id:'5', 
            name:'Puma Slim pant',
            category: 'Shirts',
            image:'./images/p5.jpg', 
            price:140,
            brand:'Puma', 
            rating:5, 
            numReviews:10,
            description:'hight quality product',
        },
    ]
}
export default data;